# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "CREATE Workshop: Building a Personal Site using Github Pages"
email: create@createunsw.com.au
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/github-pages-workshop" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  _slides:
    output: true
    permalink: /slides/:title/

defaults:
  -
    scope:
      path: "__slides"
    values:
      layout: "slide"

# github runs jekyll 3.9.0, specifying order requires 4.1.0. This is a fine workaround
slide_order:
  - Introduction
  - Acknowledgement_of_Country
  - About_CREATE
  - Jack
  - Assumed_Knowledge
  - Static_Sites
  - Github_Pages
  - Technologies
  - HTML
  - CSS
  - SASS
  - Javascript
  - Setup
  - Config
  - Profile
  - Markdown
  - Jekyll
  - Liquid
  - Layout
  - Collections
  - Projects
  - Blog
  - Advanced_Stuff
  - Going_Further
  - Resources

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
