# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "CREATE Workshop: Making a Personal Site from scratch with Github Pages"
email: create@createunsw.com.au
description: Welcome to CREATE Workshop on building your very own personal website using Github Pages.
baseurl: /github-pages-workshop
url: "" # the base hostname & protocol for your site, e.g. http://example.com

favicon: /images/logos/favicon.png

# logos
logo-pos: /images/logos/create.png
logo-neg: /images/logos/create-neg.png

main_website: https://www.createunsw.com.au
facebook_username: createunsw
youtube_link: https://www.youtube.com/channel/UCUo89qrPI3aoLo5bWTiPfZQ

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed

collections:
  _slides:
    output: true
    permalink: /slides/:title/

defaults:
  -
    scope:
      path: "__slides"
    values:
      layout: "slide"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
